import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { format } from 'date-fns';
import { getScanByShareToken } from '@/lib/supabase/queries';
import SharedReportContent from './SharedReportContent';

interface SharedReportPageProps {
  params: Promise<{ token: string }>;
}

export async function generateMetadata({
  params,
}: SharedReportPageProps): Promise<Metadata> {
  const { token } = await params;
  const { data } = await getScanByShareToken(token);

  if (!data) {
    return { title: 'Report Not Found - AccessAudit' };
  }

  return {
    title: `Accessibility Report — ${data.siteName} - AccessAudit`,
    description: `WCAG 2.1 AA compliance scan results for ${data.siteUrl}. Score: ${data.scan.score ?? 'N/A'}/100.`,
  };
}

export default async function SharedReportPage({
  params,
}: SharedReportPageProps) {
  const { token } = await params;

  // Validate token format (24 alphanumeric characters)
  if (!/^[A-Za-z0-9]{24}$/.test(token)) {
    notFound();
  }

  const { data, error } = await getScanByShareToken(token);

  if (error || !data) {
    notFound();
  }

  const { scan, violations, siteName, siteUrl } = data;

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="border-b border-gray-200 bg-white">
        <div className="mx-auto max-w-5xl px-4 py-4 sm:px-6">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-xs font-medium uppercase tracking-wider text-gray-400">
                Shared Compliance Report
              </p>
              <h1 className="mt-1 text-lg font-semibold text-gray-900">
                {siteName}
              </h1>
            </div>
            <div className="text-right">
              <p className="text-xs text-gray-400">Scanned on</p>
              <p className="text-sm font-medium text-gray-700">
                {format(new Date(scan.created_at), 'MMM d, yyyy')}
              </p>
            </div>
          </div>
        </div>
      </header>

      {/* Content */}
      <main className="mx-auto max-w-5xl px-4 py-8 sm:px-6">
        <SharedReportContent
          scan={scan}
          violations={violations}
          siteName={siteName}
          siteUrl={siteUrl}
        />
      </main>

      {/* Footer */}
      <footer className="border-t border-gray-200 bg-white">
        <div className="mx-auto max-w-5xl px-4 py-4 sm:px-6">
          <p className="text-center text-xs text-gray-400">
            Generated by AccessAudit — Accessibility compliance monitoring
          </p>
        </div>
      </footer>
    </div>
  );
}
